repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict

- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black
    additional_dependencies: ["tomli"]
    args: ["--line-length=100"]
    stages: [commit]
    files: ^segus_engineering_Backend/

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    stages: [commit]
    files: ^segus_engineering_Backend/

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.6.9
  hooks:
  - id: ruff
    args: ["--fix"]
    stages: [commit]
    files: ^segus_engineering_Backend/

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v9.13.0
  hooks:
  - id: eslint
    args: ["--max-warnings=0"]
    additional_dependencies:
      - eslint@9
      - prettier
      - eslint-config-prettier
      - eslint-plugin-prettier
      - @angular-eslint/eslint-plugin
      - @angular-eslint/eslint-plugin-template
      - @angular-eslint/template-parser
      - @typescript-eslint/parser
      - @typescript-eslint/eslint-plugin
    files: ^Segus_Engineering_Frontend/


