[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["segus_engineering_Backend", "users", "employees", "projects", "jobs", "gamification", "chatbot", "site_content", "notifications", "contact_messages", "realtime"]
skip = ["migrations", "env", "venv", "build", "dist", "__pycache__"]





