# Generated by Django 5.2.4 on 2025-07-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("ACTIVE", "Actif"), ("INACTIVE", "Inactif")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "employes",
                    models.ManyToManyField(related_name="projets", to="employees.employee"),
                ),
            ],
        ),
    ]
