# Generated by Django 5.2.4 on 2025-08-03 11:19

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="date_debut",
        ),
        migrations.RemoveField(
            model_name="project",
            name="date_fin",
        ),
        migrations.RemoveField(
            model_name="project",
            name="employes",
        ),
        migrations.RemoveField(
            model_name="project",
            name="statut",
        ),
        migrations.RemoveField(
            model_name="project",
            name="titre",
        ),
        migrations.AddField(
            model_name="project",
            name="assigned_employees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Employés assignés",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(default=datetime.date(2025, 8, 3), verbose_name="Date de fin"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(default="2025-12-31", verbose_name="Date de début"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Actif"),
                    ("COMPLETED", "Terminé"),
                    ("PAUSED", "En pause"),
                    ("CANCELLED", "Annulé"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title",
            field=models.CharField(default="2025-12-31", max_length=200, verbose_name="Titre"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "À faire"),
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminée"),
                            ("BLOCKED", "Bloquée"),
                        ],
                        default="TODO",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Basse"),
                            ("MEDIUM", "Moyenne"),
                            ("HIGH", "Haute"),
                            ("URGENT", "Urgente"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Priorité",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_employees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employés assignés",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tâche",
                "verbose_name_plural": "Tâches",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_name",
                    models.CharField(max_length=200, verbose_name="Nom de la section"),
                ),
                (
                    "section_number",
                    models.CharField(max_length=50, verbose_name="Numéro de section"),
                ),
                (
                    "section_id",
                    models.CharField(max_length=100, verbose_name="Identifiant de section"),
                ),
                (
                    "kilometrage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Kilométrage correspondant à la section",
                        max_digits=10,
                        verbose_name="Kilométrage",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Terminée"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Terminée le"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_employees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_subtasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employés assignés",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_subtasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="projects.task",
                        verbose_name="Tâche",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-tâche",
                "verbose_name_plural": "Sous-tâches",
                "ordering": ["section_number"],
            },
        ),
    ]
