# Generated by Django 5.2.4 on 2025-08-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_options_employee_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
    ]
