# Generated by Django 5.2.4 on 2025-08-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0010_add_pause_fields_to_worksession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="department",
        ),
    ]
