# Generated by Django 5.2.4 on 2025-08-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0011_remove_department_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worksession",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
    ]
