# Generated by Django 5.2.4 on 2025-08-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYE', 'Employé')], default='EMPLOYE', max_length=50),
        ),
    ]
