# Generated by Django 5.2.4 on 2025-08-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Administrateur"), ("EMPLOYE", "Employé")],
                default="EMPLOYE",
                max_length=20,
            ),
        ),
    ]
