# Generated by Django 5.2.4 on 2025-08-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/', verbose_name='Photo de profil'),
        ),
    ]
