# Generated by Django 5.2.4 on 2025-09-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_passwordresetcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Adresse"),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date de naissance"),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Contact d'urgence"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Téléphone d'urgence"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculin"), ("F", "Féminin")],
                max_length=1,
                null=True,
                verbose_name="Genre",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Téléphone"),
        ),
    ]
