---
- name: Deploy SEGUS Engineering
  hosts: web_servers
  become: yes
  vars:
    app_name: segus-engineering
    docker_compose_file: docker-compose.yml
  
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: yes
    
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    
    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present
    
    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
    
    - name: Create app directory
      file:
        path: /opt/{{ app_name }}
        state: directory
        mode: '0755'
    
    - name: Copy docker-compose file
      copy:
        src: "{{ docker_compose_file }}"
        dest: /opt/{{ app_name }}/{{ docker_compose_file }}
    
    - name: Pull latest images
      docker_compose:
        project_src: /opt/{{ app_name }}
        pull: yes
    
    - name: Start services
      docker_compose:
        project_src: /opt/{{ app_name }}
        state: present
        recreate: always