---
- name: Deploy SEGUS Engineering
  hosts: web_servers
  become: true
  collections:
    - community.docker
  vars:
    app_name: segus-engineering
    docker_compose_file: docker-compose.yml

  tasks:
    - name: Update system packages
      apt:
        update_cache: true
        upgrade: true

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose v2 plugin
      apt:
        name: docker-compose-plugin
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Create app directory
      file:
        path: /opt/{{ app_name }}
        state: directory
        mode: '0755'

    - name: Copy docker-compose file
      copy:
        src: "{{ docker_compose_file }}"
        dest: /opt/{{ app_name }}/{{ docker_compose_file }}

    - name: Pull latest images
      community.docker.docker_compose_v2:
        project_src: /opt/{{ app_name }}
        pull: true

    - name: Start services
      community.docker.docker_compose_v2:
        project_src: /opt/{{ app_name }}
        state: present
        recreate: true