# Generated by Django 5.2.4 on 2025-07-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("TEXT", "Texte"), ("IMAGE", "Image")],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
            ],
        ),
    ]
